name: ammo-model
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - cmdstan=2.33.1
  - cmdstanpy=1.2.4
  - colorama=0.4.6
  - contourpy=1.2.1
  - convertdate=2.4.0
  - cpuonly=2.0
  - cycler=0.12.1
  - ephem=4.1.5
  - filelock=3.15.4
  - fonttools=4.53.1
  - freetype=2.12.1
  - h2=4.1.0
  - holidays=0.54
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib_resources=6.4.0
  - intel-openmp=2024.2.0
  - jinja2=3.1.4
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.21
  - libexpat=2.6.2
  - libffi=3.4.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lunarcalendar=0.0.9
  - m2-bash=4.3.042
  - m2-coreutils=8.25
  - m2-filesystem=2016.04
  - m2-gcc-libs=5.3.0
  - m2-gmp=6.1.0
  - m2-libiconv=1.14
  - m2-libintl=0.19.7
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-sed=4.2.2
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.5.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - networkx=3.3
  - numpy=2.0.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - patsy=0.5.6
  - pillow=10.4.0
  - pip=24.2
  - prophet=1.1.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pycparser=2.22
  - pymeeus=0.5.12
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytorch=2.4.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - requests=2.32.3
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=72.1.0
  - six=1.16.0
  - stanio=0.5.1
  - statsmodels=0.14.2
  - sympy=1.13.0
  - tabulate=0.9.0
  - tbb=2021.12.0
  - tk=8.6.13
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - tqdm=4.66.5
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.2.2
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.19.2
  - zstandard=0.23.0
  - zstd=1.5.6
